using System;
//http://habrahabr.ru/post/148852/
namespace midi
{
	public struct Note
	{
		public byte Octave;
		public Tones Tone;
		public int Id;
		public Note(byte oct, Tones t)
		{
			Octave = oct;
			Tone = t;
			Id = 12 + Octave * 12 + (int)Tone;
		}
		public Note(byte oct, string t) : this(oct, (Tones)Enum.Parse(typeof(Tones), t)){ }
		public Note(byte oct, char t) : this(oct, new string(t, 1)) { }
	}

	// ReSharper disable InconsistentNaming
	public enum Tones
	{
		a = 9, A = 10, b = 11, c = 0, C = 1,d = 2, D = 3, e = 4, f = 5, F = 6, g = 7, G = 8
	}
	public enum Instruments
	{
		AcousticPiano,
		BriteAcouPiano,
		ElectricGrandPiano,
		HonkyTonkPiano,
		ElecPiano1,
		ElecPiano2,
		Harsichord,
		Clavichord,
		Celesta,
		Glockenspiel,
		MusicBox,
		Vibraphone,
		Marimba,
		Xylophone,
		TubularBells,
		Dulcimer,
		DrawbarOrgan,
		PercOrgan,
		RockOrgan,
		ChurchOrgan,
		ReedOrgan,
		Accordian,
		Harmonica,
		TangoAccordian,
		AcousticGuitar,
		SteelAcousGuitar,
		ElJazzGuitar,
		ElectricGuitar,
		ElMutedGuitar,
		OverdrivenGuitar,
		DistortionGuitar,
		GuitarHarmonic,
		AcousticBass,
		ElBassFinger,
		ElBassPick,
		FretlessBass,
		SlapBass1,
		SlapBass2,
		SynthBass1,
		SynthBass2,
		Violin,
		Viola,
		Cello,
		ContraBass,
		TremeloStrings,
		PizzStrings,
		OrchStrings,
		Timpani,
		StringEns1,
		StringEns2,
		SynthStrings1,
		SynthStrings2,
		ChoirAahs,
		VoiceOohs,
		SynthVoice,
		OrchestraHit,
		Trumpet,
		Trombone,
		Tuba,
		MutedTrumpet,
		FrenchHorn,
		BrassSection,
		SynthBrass1,
		SynthBrass2,
		SopranoSax,
		AltoSax,
		TenorSax,
		BaritoneSax,
		Oboe,
		EnglishHorn,
		Bassoon,
		Clarinet,
		Piccolo,
		Flute,
		Recorder,
		PanFlute,
		BlownBottle,
		Shakuhachi,
		Whistle,
		Ocarina,
		Lead1Square,
		Lead2Sawtooth,
		Lead3Calliope,
		Lead4Chiff,
		Lead5Charang,
		Lead6Voice,
		Lead7Fifths,
		Lead8BassLd,
		Pad1NewAge,
		Pad2Warm,
		Pad3Polysynth,
		Pad4Choir,
		Pad5Bowed,
		Pad6Metallic,
		Pad7Halo,
		Pad8Sweep,
		FX1Rain,
		FX2Soundtrack,
		FX3Crystal,
		FX4Atmosphere,
		FX5Brightness,
		FX6Goblins,
		FX7Echoes,
		FX8SciFi,
		Sitar,
		Banjo,
		Shamisen,
		Koto,
		Kalimba,
		Bagpipe,
		Fiddle,
		Shanai,
		TinkerBell,
		Agogo,
		SteelDrums,
		Woodblock,
		TaikoDrum,
		MelodicTom,
		SynthDrum,
		ReverseCymbal,
		GuitarFretNoise,
		BreathNoise,
		Seashore,
		BirdTweet,
		Telephone,
		Helicopter,
		Applause,
		Gunshot
	}
}
